# Example recipients configuration for `paper-firehose email`.
# Update the addresses and topic lists before enabling.
recipients:
  - to: "researcher@example.com"
    topics: ["example"]
    mode: "auto"
    limit: 5
  - to: "team@example.com"
    topics: ["example"]
    mode: "ranked"
    min_rank_score: 0.5
