name: "Catalysis, 2D metals"
description: "Catalysis, 2D metals"

# Which feeds to process for this topic
feeds:
  - "cond-mat"
  - "nature"
  - "science"
  - "nat-mat"
  - "nat-nanotech"
  - "nat-phys"
  - "nat-chem"
  - "nat-ener"
  - "nat-catal"
  - "nat-chem-eng"
  - "nat-rev-phys"
  - "pnas"
  - "joule"
  - "prb"
  - "prl"
  - "prx"
  - "pr_res"
  - "nano-lett"
  - "acs-nano"
  - "acs-en-lett"
  - "en-env-sci"
  - "science-adv"
  - "sci-rep"
  - "nat-comm"
  - "comm-phys"
  - "comm-mater"
  - "scipost"
  - "small"
  - "adv-mater"
  - "adv-sci"
  - "adv-func-mater"
  - "adv-phys-res"
  - "national-sci-rev"
  - "npj-2d-mater"
  - "npj-comp-mater"
  - "npj-qmat"

# Regex filter
filter:
  pattern: "(MoS.+\d+|MoS\d+)|\
            (MoSe.+\d+|MoSe\d+)|\
            (MoTe.+\d+|MoTe\d+)|\
            (WS.+\d+|WS\d+)|\
            (WSe.+\d+|WSe\d+)|\
            (WTe.+\d+|WTe\d+)|\
            (NbSe\d+)|\
            (PdTe\d+)|\
            (Mo[\s-]*dichalcogenid[a-z]+)|\
            (W[\s-]*dichalcogenid[a-z]+)|\
            (transition[\s-]*metal[\s-]*dichalcogenid[a-z]+)|\
            (Pt[a-z]*|platinum)|\
            (platinum[\s-]*nanopartic[a-z]+)|\
            (Bi|bismuth)|\
            (Ga|gallium)|\
            (In|indium)|\
            (Sn|tin)|\
            (Pb|lead)|\
            (stanene)|\
            (bismuthene)|\
            (antimonene)|\
            (goldene)|\
            (2D[\s-]*metal[a-z]*)|\
            (hydrogen[\s-]*evolution[\s-]*reaction)|\
            (H2[\s-]*product[a-z]*)|\
            (catalys[a-z]+)|\
            (electrocatalys[a-z]+)|\
            (Faradaic[\s-]*efficienc[a-z]*)|\
            (nonmetallic[\s-]*electronic[\s-]*struct[a-z]*)|\
            (STM)|\
            (scan[a-z]+ tunne[a-z]+ micr[a-z]+)"
  fields: ["title", "summary"]

# Ranking configuration
ranking:
  query: >   # Natural-language ranking query used for sentence-transformers similarity
    MoS2 MoSe2 MoTe2 WS2 WSe2 WTe2
    dichalcogenide
    transition metal dichalcogenides
    TMDC
    2D metal
    elemental monolayer
    Pt platinum
    platinum nanoparticle
    Pt bilayer, semiconducting Pt
    Angstrom-thick metals
    hydrogen evolution reaction (HER)
    catalysis
    electrocatalysis
    scanning tunneling microscopy (STM)

  # Optional additional negative phrases to downweight (list may be empty)
  negative_queries: [erratum, correction, reply, corrigendum]

  # Preferred authors. Names in this list get a ranking boost. Order: First name (or initial), Last name.
  preferred_authors: []
  priority_author_boost: 0.1

  # Sentence-Transformers model used for ranking (can be overridden per topic)
  model: "all-MiniLM-L6-v2" # with this model input text longer than 256 word pieces is truncated.

# Abstract fetch configuration
abstract_fetch:
  enabled: true
  rank_threshold: 0.25 # this overrides the global rank_threshold in config.yaml. Should be smaller than score_cutoff

# LLM summary configuration
llm_summary:
  enabled: true
  prompt: > # Uses ranking_query from the ranking configuration to assess topical relevance
    You are a world-class condensed-matter researcher specializing in 2D van der Waals materials,
    STM, and catalysis. 
    Focus on topical relevance (2D metals, catalysis), novelty/impact, and experimental/theory significance.
    Be concise and expert-focused. Keep text concise and information-dense.
    Avoid using superlatives and other over-the-top language.
    CRITICAL: Return ONLY valid JSON with the exact structure specified.
    No markdown formatting, no explanations, no text before or after the JSON object.
    Required JSON structure:
    {
      "summary": "Brief technical summary of the paper",
      "topical_relevance": "Assessment of relevance to: {ranking_query}, in one sentence",
      "novelty_impact": "Evaluation of novelty and potential impact"
    }
  # Cutoffs: strongest cutoff applies (the one returning the fewest entries)
  # score_cutoff: minimum cosine similarity (0.0–1.0)
  score_cutoff: 0.3
  # Top N papers to return, hard cutoff after score_cutoff
  top_n: 10

# Output configuration
output:
  filename: "results_2d_metals.html"
  filename_ranked: "results_2d_metals_ranked.html"
  filename_summary: "results_2d_metals_summary.html"
  archive: true # archive the output file to the "matched_entries_history.db" database
