name: "Rhombohedral Graphite"
description: "ABC-stacked graphene multilayers"

feeds:
  - "cond-mat"
  - "nature"
  - "science"
  - "nat-mat"
  - "nat-nanotech"
  - "nat-phys"
  - "nat-chem"
  - "nat-ener"
  - "nat-catal"
  - "nat-chem-eng"
  - "nat-rev-phys"
  - "pnas"
  - "joule"
  - "prb"
  - "prl"
  - "prx"
  - "pr_res"
  - "nano-lett"
  - "acs-nano"
  - "acs-en-lett"
  - "en-env-sci"
  - "science-adv"
  - "sci-rep"
  - "nat-comm"
  - "comm-phys"
  - "comm-mater"
  - "scipost"
  - "small"
  - "adv-mater"
  - "adv-sci"
  - "adv-func-mater"
  - "adv-phys-res"
  - "national-sci-rev"

filter:
  pattern: "(rhombohedr[a-z]+.*graph[a-z]+)|(ABC.*graph[a-z]+)|(ABC.*trilay[a-z]+)|(ABCA.*tetralay[a-z]+)|(ABCB.*tetralay[a-z]+)|(tetralay[a-z]+.*graph[a-z]+)|(pentalay[a-z]+.*graph[a-z]+)|(graph[a-z]+.*pentalay[a-z]+)|(hexalay[a-z]+.*graph[a-z]+)|(graph[a-z]+.*hexalay[a-z]+)|(heptalay[a-z]+.*graph[a-z]+)|(graph[a-z]+.*heptalay[a-z]+)"
  fields: ["title", "summary"]

ranking:
  prompt: >
    You are a world-class condensed-matter researcher with deep expertise in rhombohedral graphite (ABC-stacked graphene multilayers) and related STM/transport phenomena. 
    Prioritize entries that directly concern ABC/rhombohedral stacking, few-layer graphene with rhombohedral domains, or unambiguous experimental/theory advances in this subfield.
  # Natural-language ranking query used for sentence-transformers similarity
  query: >
    Rhombohedral graphite, rhombohedral stacking, rhombohedral multilayer graphene,
    ABC-stacked graphene, ABC stacking, trilayer, tetralayer, pentalayer, hexalayer,
    heptalayer graphene, chiral graphene

  # Optional additional negative phrases to downweight (list may be empty)
  negative_queries: []

  # Sentence-Transformers model used for ranking (can be overridden per topic)
  model: "all-MiniLM-L6-v2"

  # Cutoffs: strongest cutoff applies (the one returning the fewest entries)
  # - score_cutoff: minimum cosine similarity (0.0–1.0); default 0.2
  # - percentile_cutoff: keep top X% by score within the candidate set; default 0.30 (top 30%)
  score_cutoff: 0.2
  percentile_cutoff: 0.30
  top_n: 5

output:
  filename: "rg_filtered_articles.html"
  archive: true
