name: "Primary Research"
description: "Topological materials, graphene, and condensed matter physics"

# Which feeds to process for this topic
feeds:
  - "cond-mat"
  - "nature"
  - "science"
  - "nat-mat"
  - "nat-nanotech"
  - "nat-phys"
  - "nat-chem"
  - "nat-ener"
  - "nat-catal"
  - "nat-chem-eng"
  - "nat-rev-phys"
  - "pnas"
  - "joule"
  - "prb"
  - "prl"
  - "prx"
  - "pr_res"
  - "nano-lett"
  - "acs-nano"
  - "acs-en-lett"
  - "en-env-sci"
  - "science-adv"
  - "sci-rep"
  - "nat-comm"
  - "comm-phys"
  - "comm-mater"
  - "scipost"
  - "small"
  - "adv-mater"
  - "adv-sci"
  - "adv-func-mater"
  - "adv-phys-res"
  - "national-sci-rev"

# Regex filter
filter:
  pattern: "parametric oscillation"
  fields: ["title", "summary"]

# Ranking configuration
ranking:
  prompt: "You are a world-class condensed-matter researcher specializing in 
    graphene. Focus on topical relevance (graphene), 
    novelty/impact, and experimental/theory significance."
  # Natural-language ranking query used for sentence-transformers similarity
  query: "Parametric oscillation in condensed matter/optical systems"

  # Optional additional negative phrases to downweight (list may be empty)
  negative_queries: []

  # Sentence-Transformers model used for ranking (can be overridden per topic)
  model: "all-MiniLM-L6-v2"

  # Cutoffs: strongest cutoff applies (the one returning the fewest entries)
  # - score_cutoff: minimum cosine similarity (0.0–1.0); default 0.2
  # - percentile_cutoff: keep top X% by score within the candidate set; default 0.30 (top 30%)
  score_cutoff: 0.2
  percentile_cutoff: 0.30
  top_n: 5

# Output configuration
output:
  filename: "results_testtopic2.html"
  template: "testtopic2_summary.html"
  archive: true # archive the output file to the "matched_entries_history.db" database
